services:
  - type: web
    name: workbridge
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: null
        sync: false
      - key: DB_HOST
        value: null
        sync: false
      - key: DB_PORT
        value: null
        sync: false
      - key: DB_NAME
        value: null
        sync: false
      - key: DB_USER
        value: null
        sync: false
      - key: DB_PASS
        value: null
        sync: false
      - key: SESSION_SECRET
        value: null
        sync: false
